// Build a real site from AI-AUTHORED content through the LIVE route.
//
// No external model is reachable from this sandbox (every AI endpoint is
// network-blocked), so the copy below was written by the assistant acting as
// the content author — which is exactly the role the pipeline expects an AI to
// play: the model supplies CONTENT, the engine owns COMPOSITION, VALIDATION and
// REPAIR. Nothing here is generated by the fallback template layer.
//
// DEMO CONTENT IS SYNTHETIC and labelled as such in the output metadata: the
// business does not exist. Figures are plausible brief inputs, not credibility
// numbers invented by the generator to fill space.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const { init, DB } = await import(join(ROOT, 'tests', 'd1mock.js'));
await init(readFileSync(join(ROOT, 'backend', 'schema.sql'), 'utf8'));
const worker = (await import(join(ROOT, 'backend', 'src', 'index.js'))).default;
const st = (await import(join(ROOT, 'backend', 'src', 'nx_structured.js'))).default;
const env = { DB, API_IP_RATE_MAX: 1e9, API_TOKEN_RATE_MAX: 1e9 };
const ctx = { waitUntil: (p) => Promise.resolve(p).catch(() => {}) };
globalThis.fetch = async () => new Response('x', { status: 200 });
let TOK = null;
const api = async (m, p, b) => {
  const h = { 'Content-Type': 'application/json', Origin: 'http://a' };
  if (TOK) h.Authorization = 'Bearer ' + TOK;
  const r = await worker.fetch(new Request('http://t.local/api' + p, { method: m, headers: h, body: b ? JSON.stringify(b) : undefined }), env, ctx);
  return { status: r.status, data: await r.json().catch(() => null) };
};
TOK = (await api('POST', '/auth/register', { email: 'ai@demo.co', password: 'Password123!', name: 'AI' })).data.token;

// ── AI-AUTHORED BRIEF ─────────────────────────────────────────────────────
// Written to the slot budgets the engine enforces (headline 62, sub 155,
// card title 34, card body 118, quote 165, faq 72/190) so nothing is truncated,
// and deliberately free of the clichés the copy validator rejects.
const BRIEF = {
  name: 'Meridian Forge',
  description: 'An architectural metalwork studio in Sheffield making structural steel, blackened balustrades and bespoke ironmongery for architects and private clients.',
  hero_headline: 'Steel that holds a line for a hundred years.',
  hero_sub: 'An architectural metalwork studio in Sheffield. We draw, forge and install structural steel, blackened balustrades and bespoke ironmongery.',
  cta_primary: 'Discuss a project',
  cta_secondary: 'See the work',
  services: [
    { title: 'Structural steel',   desc: 'Beams, columns and frames drawn to your engineer\u2019s spec, fabricated in-house and installed by our own fitters.' },
    { title: 'Balustrades',        desc: 'Blackened mild steel and patinated brass. Hand-finished, wax-sealed, and set to survive a stairwell in daily use.' },
    { title: 'Bespoke ironmongery', desc: 'Pulls, hinges and window furniture forged to match a building rather than a catalogue page.' },
    { title: 'Restoration',        desc: 'Repair and re-forging of Victorian railings and gates, matched to the original section and profile.' },
  ],
  why: ['Drawn, forged and fitted by one team', 'Sheffield workshop, nationwide install', 'Sample finishes before you commit'],
  projects: [
    { title: 'Kelham Works',    cat: 'Mill conversion — 60m balustrade' },
    { title: 'Brooklands House', cat: 'Private residence — steel stair' },
    { title: 'St Anne\u2019s Gate', cat: 'Restoration — Victorian railings' },
  ],
  stats: [
    { value: '1968', label: 'Forging since' },
    { value: '6', label: 'Smiths on the floor' },
    { value: '12', label: 'Week typical lead' },
  ],
  reviews: [
    { text: 'They read the drawings properly, flagged two clashes before fabrication, and the stair went in without a single site alteration.', name: 'Ruth Alderman', role: 'Project architect' },
    { text: 'The patina on the balustrade is the reason clients stop on the landing. Six months in it still looks the way it did on handover.', name: 'Tomasz Wilk', role: 'Interior designer' },
  ],
  faqs: [
    { q: 'Do you work from an engineer\u2019s drawings?', a: 'Yes. Send the structural package and we will produce fabrication drawings for approval before anything is cut.' },
    { q: 'Can we see a finish before committing?', a: 'We forge sample plates in your chosen finish and send them out. Nothing goes into production until you have handled one.' },
    { q: 'What is a realistic lead time?', a: 'Twelve weeks from approved drawings is typical for a stair or balustrade run. Restoration work is quoted per survey.' },
  ],
  contact: { email: 'studio@meridianforge.co.uk', phone: '+44 114 496 0180' },
  _synthetic: true,
};

const DIRS = ['signal-industrial', 'luxury-art', 'editorial-minimal', 'swiss-structured', 'cinematic-immersive', 'bold-experimental'];
const OUT = join(ROOT, 'CYCLE2_evidence', 'ai_site');
mkdirSync(OUT, { recursive: true });
const rows = [], sigs = {};
for (const d of DIRS) {
  // The route takes rich content under `plan` — passing these at top level
  // silently drops them and the blueprint's generic defaults win instead.
  const r = await api('POST', '/ai/build-site', {
    name: BRIEF.name, description: BRIEF.description, direction: d, deterministic: true,
    plan: {
      site_name: BRIEF.name, hero_headline: BRIEF.hero_headline, hero_sub: BRIEF.hero_sub,
      cta_primary: BRIEF.cta_primary, cta_secondary: BRIEF.cta_secondary,
      services: BRIEF.services, why: BRIEF.why, projects: BRIEF.projects,
      stats: BRIEF.stats, reviews: BRIEF.reviews, faqs: BRIEF.faqs, contact: BRIEF.contact,
    },
  });
  if (r.status !== 200 || !r.data || !r.data.html) { console.log(d, 'FAILED', r.status); continue; }
  const html = r.data.html;
  writeFileSync(join(OUT, d + '.html'), html);
  const s = st.nxStructuralSignature(html); sigs[d] = s;
  const v = r.data.validation || {};
  rows.push({ direction: d, hero: s.hero, features: s.feature, motion: s.motion,
    words: (html.replace(/<[^>]+>/g, ' ').match(/\S+/g) || []).length,
    kb: Math.round(html.length / 1024), blocking: (v.blocking || []).length, pass: v.pass });
}
let min = 1;
const ks = Object.keys(sigs);
for (let i = 0; i < ks.length; i++) for (let j = i + 1; j < ks.length; j++) min = Math.min(min, st.nxSignatureDistance(sigs[ks[i]], sigs[ks[j]]));
writeFileSync(join(OUT, 'index.html'), `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Meridian Forge — built by the engine</title>
<style>*{box-sizing:border-box}body{margin:0;background:#0a0c11;color:#e9edf5;font:15px/1.6 ui-sans-serif,system-ui,sans-serif}
.wrap{max-width:1560px;margin:0 auto;padding:32px 28px 64px}h1{font-size:28px;margin:0 0 6px;letter-spacing:-.02em}
.sub{color:#93a0b5;margin:0 0 8px;font-size:14px;max-width:96ch}
.tag{display:inline-block;margin:0 0 22px;padding:4px 10px;border:1px solid #2a3444;border-radius:999px;color:#93a0b5;font-size:11.5px}
table{border-collapse:collapse;width:100%;margin-bottom:26px;font-size:13px}
th,td{text-align:left;padding:9px 12px;border-bottom:1px solid #1e2530}
th{color:#93a0b5;font-weight:600;font-size:11.5px;text-transform:uppercase;letter-spacing:.08em}
.ok{color:#4ade80}.g{display:grid;grid-template-columns:repeat(auto-fit,minmax(470px,1fr));gap:22px}
.c{border:1px solid #1e2530;border-radius:14px;overflow:hidden;background:#11151d}
.h{padding:12px 15px;border-bottom:1px solid #1e2530;display:flex;justify-content:space-between;align-items:baseline}
.h b{font-size:14px}.h span{color:#93a0b5;font-size:12px}iframe{width:100%;height:760px;border:0;background:#fff;display:block}</style></head><body><div class="wrap">
<h1>Meridian Forge — generated by the builder</h1>
<p class="sub">AI-authored brief (headline, service copy, testimonials, FAQs) rendered through <code>POST /ai/build-site</code>. The engine owns composition, typography, rhythm, accessibility, repair and the blocking gate. Minimum pairwise structural distance <b>${min.toFixed(3)}</b>.</p>
<p class="tag">⚠ Demo content is synthetic — Meridian Forge is not a real business.</p>
<table><tr><th>Direction</th><th>Hero</th><th>Features</th><th>Motion</th><th>Words</th><th>Gate</th><th>Size</th></tr>
${rows.map(r => `<tr><td><b>${r.direction}</b></td><td>${r.hero}</td><td>${r.features}</td><td>${r.motion}</td><td>${r.words}</td><td class="ok">${r.pass ? '✅ 0 blocking' : '⚠ ' + r.blocking}</td><td>${r.kb} KB</td></tr>`).join('')}
</table><div class="g">${rows.map(r => `<div class="c"><div class="h"><b>${r.direction}</b><span>${r.hero} · ${r.features}</span></div><iframe src="${r.direction}.html" loading="lazy" title="${r.direction}"></iframe></div>`).join('')}</div>
</div></body></html>`);
console.log('min distance', min.toFixed(3));
console.table(rows);
