// Extracted craft/anti-slop rules loaded into the AI system prompt.
export const CRAFT_PROMPT_FRAGMENT: string = [
  "--- ACCESSIBILITY-BASELINE ---",
  "## Focus & keyboard",
  "- All interactive elements must be keyboard focusable.",
  "- Visible focus ring: `focus-visible:ring-2 ring-offset-2` on primary actions.",
  "- Contrast AA minimum everywhere.",
  "- Never use color alone to convey meaning.",
  "",
  "--- COLOR ---",
  "- Pick one accent, one surface, one text color per system.",
  "- Use design tokens (`var(--accent)`, `var(--surface)`) — never hard hex inside components.",
  "- Absolute maximum 3 visible accent applications per screen.",
  "",
  "--- TYPOGRAPHY ---",
  "- Display fonts only on H1/H2.",
  "- Display headings get NEGATIVE letter-spacing (-0.01em to -0.03em).",
  "- ALL-CAPS needs positive tracking (+0.06em to +0.1em).",
  "- Body text is 15-18px, line-height 1.5-1.6, max-width 65ch.",
  "- Cap at 3 visible sizes above the fold.",
  "- Never end a sentence with a period in a button or label.",
  "",
  "--- ANTI-AI-SLOP ---",
  "- NO default Tailwind indigo accent (#6366f1, #4f46e5, #4338ca, #3730a3, #8b5cf6, #7c3aed, #a855f7).",
  "- NO two-stop 'trust' purple→blue / blue→cyan gradient on heroes.",
  "- NO emoji-as-icon (✨🚀🎯⚡🔥💡) — clean SVG only.",
  "- NO fake metrics ('10x faster', '99.9% uptime').",
  "- NO lorem ipsum. Real, specific, plausible copy only.",
  "- Accent color ≤ 2 times per screen.",
  "- Honeycomb of authentic detail: brand terms, section names, handwriting, humans in photos.",
  "",
  "--- ANIMATION & MOTION ---",
  "- Ease-out on enter (150-300ms), ease-in on exit (100-200ms).",
  "- Never animate transform + opacity simultaneously for > 250ms.",
  "- Respect prefers-reduced-motion.",
].join("\n");
