// AUTO-GENERATED — 114 design templates from Open Design 0.21
export interface DesignTemplate { id: string; name: string; description: string; mode: string; tags: string[]; triggers?: string[] }
export const DESIGN_TEMPLATES: DesignTemplate[] = [
  {
    "id": "audio-jingle",
    "name": "audio-jingle",
    "description": "| Audio generation skill — jingles, beds, voiceover, and sound effects. Routes music requests to Suno V5 / Udio / Lyria, speech to MiniMax TTS / FishAudio / ElevenLabs V3, and SFX to ElevenLabs SFX or",
    "mode": "audio",
    "tags": [],
    "triggers": [
      "\"music\"",
      "\"jingle\"",
      "\"bed\"",
      "\"voiceover\"",
      "\"tts\"",
      "\"sound effect\"",
      "\"音乐\"",
      "\"配音\"",
      "\"音效\"",
      "od:",
      "mode: audio",
      "surface: audio"
    ]
  },
  {
    "id": "blog-post",
    "name": "blog-post",
    "description": "| A long-form article / blog post — masthead, hero image placeholder, article body with figures and pull quotes, author byline, related posts. Use when the brief asks for \"blog\", \"article\", \"post\", \"e",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"blog\"",
      "\"blog post\"",
      "\"article\"",
      "\"essay\"",
      "\"case study\"",
      "\"newsletter\"",
      "\"博客\"",
      "\"文章\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: marketing"
    ]
  },
  {
    "id": "clinical-case-report",
    "name": "clinical-case-report",
    "description": "| Structured medical case presentation for clinical rounds, conferences, and documentation. Generates SOAP-format or narrative case reports with physiologically accurate vitals, labs, and evidence-bas",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"case report\"",
      "\"case presentation\"",
      "\"soap note\"",
      "\"clinical case\"",
      "\"ward rounds\"",
      "\"patient presentation\"",
      "\"case summary\"",
      "\"medical case\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: healthcare"
    ]
  },
  {
    "id": "contact-widget",
    "name": "contact-widget",
    "description": "\"Self-contained floating chat widget with welcome screen, social links, meeting button, and message input. Single HTML file, zero dependencies.\" triggers: - \"contact widget\" - \"chat widget\" - \"floatin",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"contact widget\"",
      "\"chat widget\"",
      "\"floating chat\"",
      "\"live chat widget\"",
      "",
      "od:",
      "mode: \"prototype\"",
      "platform: \"desktop\"",
      "scenario: \"engineering\"",
      "preview:",
      "type: \"html\"",
      "entry: \"example.html\""
    ]
  },
  {
    "id": "critique",
    "name": "critique",
    "description": "| Run a 5-dimension expert design review on any HTML artifact in the project — Philosophy / Visual hierarchy / Detail / Functionality / Innovation, each scored 0–10. Outputs a single self-contained HT",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"critique\"",
      "\"design review\"",
      "\"design audit\"",
      "\"5 维度评审\"",
      "\"5-dim review\"",
      "\"audit my design\"",
      "\"review my deck\"",
      "\"review my landing page\"",
      "\"评审\"",
      "\"复盘\"",
      "od:",
      "mode: prototype"
    ]
  },
  {
    "id": "dashboard",
    "name": "dashboard",
    "description": "| Admin / analytics dashboard in a single HTML file. Fixed left sidebar, top bar with user/search, main grid of KPI cards and one or two charts. Use when the brief asks for a \"dashboard\", \"admin\", \"an",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"dashboard\"",
      "\"admin panel\"",
      "\"analytics\"",
      "\"control panel\"",
      "\"后台\"",
      "\"管理后台\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: operations",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "dating-web",
    "name": "dating-web",
    "description": "| A consumer-feeling dating / matchmaking dashboard — left rail navigation, ticker bar of community signals, headline KPIs, a 30-day mutual-matches bar chart, and a match-rate trend block. Editorial t",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"dating app\"",
      "\"dating site\"",
      "\"matchmaking\"",
      "\"social dashboard\"",
      "\"community dashboard\"",
      "\"consumer dashboard\"",
      "\"约会应用\"",
      "\"婚恋\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: personal"
    ]
  },
  {
    "id": "dcf-valuation",
    "name": "dcf-valuation",
    "description": "| Discounted cash flow valuation and intrinsic value analysis for public companies. Use when the brief asks for DCF, fair value, intrinsic value, price target, undervalued or overvalued analysis, or \"",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"dcf\"",
      "\"discounted cash flow\"",
      "\"intrinsic value\"",
      "\"fair value\"",
      "\"price target\"",
      "\"undervalued\"",
      "\"overvalued\"",
      "\"估值\"",
      "\"内在价值\"",
      "od:",
      "mode: prototype",
      "preview:"
    ]
  },
  {
    "id": "digital-eguide",
    "name": "digital-eguide",
    "description": "| A two-spread digital e-guide preview — page 1 is a cover (display title, author, \"What's inside\" stats, table of contents teaser); page 2 is a spread (lesson body with pull-quote and a step list). L",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"e-guide\"",
      "\"digital guide\"",
      "\"lead magnet\"",
      "\"lookbook\"",
      "\"creator guide\"",
      "\"playbook\"",
      "\"pdf guide\"",
      "\"ebook\"",
      "\"电子指南\"",
      "\"电子书\"",
      "od:",
      "mode: prototype"
    ]
  },
  {
    "id": "docs-page",
    "name": "docs-page",
    "description": "| A documentation page — inline-start nav, scrollable article body, inline-end table of contents. Use when the brief mentions \"docs\", \"documentation\", \"guide\", \"API reference\", or \"tutorial\". triggers",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"docs\"",
      "\"documentation\"",
      "\"guide\"",
      "\"tutorial\"",
      "\"api reference\"",
      "\"文档\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: engineering",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "email-marketing",
    "name": "email-marketing",
    "description": "| A brand product-launch email — masthead with wordmark, hero image block, headline lockup with skewed-italic accent, body copy, primary CTA, and a specifications grid. Pure HTML email layout (centere",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"email\"",
      "\"email template\"",
      "\"newsletter\"",
      "\"email blast\"",
      "\"product launch email\"",
      "\"mjml\"",
      "\"邮件营销\"",
      "\"邮件模板\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: marketing"
    ]
  },
  {
    "id": "eng-runbook",
    "name": "eng-runbook",
    "description": "| An engineering runbook — service overview, alerts table, dashboards links, common procedures with copy-pasteable commands, on-call rotation, and an incident-response checklist. Use when the brief me",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"runbook\"",
      "\"ops doc\"",
      "\"on-call\"",
      "\"sre doc\"",
      "\"service runbook\"",
      "\"运维手册\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: engineering",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "finance-report",
    "name": "finance-report",
    "description": "| Quarterly / monthly financial report — masthead with KPIs, revenue and burn charts, P&L summary table, top-line highlights, and an outlook paragraph. Use when the brief mentions \"financial report\", ",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"financial report\"",
      "\"finance report\"",
      "\"quarterly report\"",
      "\"p&l\"",
      "\"mrr review\"",
      "\"财报\"",
      "\"财务报告\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: finance",
      "preview:"
    ]
  },
  {
    "id": "flowai-live-dashboard-template",
    "name": "flowai-live-dashboard-template",
    "description": "| Team-management dashboard skill in the FlowAI aesthetic — three tabs (Team Members, Team Details, Activity Log), KPI stat row, member table, role distribution bar chart, online presence and activity",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"flowai dashboard\"",
      "\"team dashboard\"",
      "\"team management dashboard\"",
      "\"interactive admin dashboard\"",
      "\"workspace admin dashboard\"",
      "\"团队管理后台\"",
      "\"可交互后台\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: operations",
      "preview:"
    ]
  },
  {
    "id": "gamified-app",
    "name": "gamified-app",
    "description": "| A multi-frame gamified mobile-app prototype — three phone frames on a dark showcase stage. Frame 1: cover / poster, Frame 2: today's quests with XP ribbons and a level bar, Frame 3: quest detail. Vi",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"gamified app\"",
      "\"habit tracker\"",
      "\"rpg app\"",
      "\"level up app\"",
      "\"daily quests\"",
      "\"xp app\"",
      "\"streak app\"",
      "\"life management app\"",
      "\"游戏化\"",
      "\"习惯打卡\"",
      "od:",
      "mode: prototype"
    ]
  },
  {
    "id": "github-dashboard",
    "name": "github-dashboard",
    "description": "| GitHub repository analytics dashboard — stars, forks, contributors, issues, pull requests, recent activity, and top contributors. Use when the brief asks for a GitHub repo dashboard, open-source gro",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"github dashboard\"",
      "\"repo dashboard\"",
      "\"repository dashboard\"",
      "\"github analytics\"",
      "\"open source dashboard\"",
      "\"github growth\"",
      "\"仓库看板\"",
      "\"GitHub 看板\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: operation"
    ]
  },
  {
    "id": "guizang-ppt",
    "name": "magazine-web-ppt",
    "description": "| For marketing and gtm work: bind launches, campaigns, events, and brand plans to growth and pipeline outcomes. Built around the core query \"annual-marketing-plan\", with GTM strategy lead judgment, b",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"annual-marketing-plan\"",
      "\"marketing-gtm\"",
      "\"Write a Brand-to-Revenue Story like a Growth Strategy Lead\"",
      "\"像增长策略负责人一样写品牌到收入故事\"",
      "\"launch\"",
      "\"campaign\"",
      "\"pipeline\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "default_for: deck"
    ]
  },
  {
    "id": "hr-onboarding",
    "name": "hr-onboarding",
    "description": "| A new-hire onboarding plan as a single page — first week schedule, buddy + manager intro, learning track, equipment checklist, and \"you're set when…\" outcomes. Use when the brief mentions \"onboardin",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"onboarding\"",
      "\"new hire\"",
      "\"first week\"",
      "\"入职\"",
      "\"新员工\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: hr",
      "preview:",
      "type: html",
      "entry: index.html"
    ]
  },
  {
    "id": "html-ppt",
    "name": "html-ppt",
    "description": "| For consulting delivery work: turn diagnosis, frameworks, and project work into a client-adoptable action plan. Built around the core query \"consulting-final-deck\", with engagement manager judgment,",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"consulting-final-deck\"",
      "\"consulting\"",
      "\"Brief AI in Your Industry like a Tier-1 Consulting AI Vertical Lead\"",
      "\"像一线咨询 AI 行业负责人一样讲清行业 AI\"",
      "\"consulting-deliverable\"",
      "\"strategy\"",
      "\"client\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-course-module",
    "name": "html-ppt-course-module",
    "description": "| A first-30-days onboarding module for new hospitality hires — the behaviors, the practice, the checks, and the manager follow-up. Built as a decision-grade professional training deck for new hires, ",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"employee-onboarding-deck\"",
      "\"professional-training\"",
      "\"Build a New-Hire Onboarding Module like a Top Enablement Lead\"",
      "\"像顶级赋能负责人一样做新人培训模块\"",
      "\"training-deck\"",
      "\"workshop\"",
      "\"course-module\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-graphify-dark-graph",
    "name": "html-ppt-graphify-dark-graph",
    "description": "| OpenDesign's feature business case for the plugin marketplace: the user pain, options, tradeoffs, and the measure of success. Built as a decision-grade product management deck for PM, eng, design, l",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"pm-feature-business-case-deck\"",
      "\"product-management\"",
      "\"Write a Feature Business Case like a Principal PM\"",
      "\"像 Principal PM 一样写功能商业论证\"",
      "\"product\"",
      "\"roadmap\"",
      "\"architecture\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-hermes-cyber-terminal",
    "name": "html-ppt-hermes-cyber-terminal",
    "description": "| OpenDesign + BYOK: choosing and wiring your own model, hands-on — cost, quality, and the routing decision. Built as a decision-grade AI literacy deck for engineers, IT, applied-AI teams. en_descript",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"enterprise-ai-copilot-rollout-brief\"",
      "\"ai-literacy\"",
      "\"Run a BYOK Model-Choice Session like an Applied-AI Engineer\"",
      "\"像应用 AI 工程师一样讲 BYOK 选型\"",
      "\"ai\"",
      "\"copilot\"",
      "\"workflow\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-knowledge-arch-blueprint",
    "name": "html-ppt-knowledge-arch-blueprint",
    "description": "| OpenDesign's incident retro: the daemon-restart data bug, the root cause, the fix, and the systemic follow-ups. Built as a decision-grade product management deck for engineering, SRE, leadership. en",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"pm-feature-business-case-deck\"",
      "\"product-management\"",
      "\"Turn an Incident Retro into a Learning Deck like a Platform VP\"",
      "\"像平台 VP 一样把事故复盘写成学习稿\"",
      "\"product\"",
      "\"roadmap\"",
      "\"architecture\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-obsidian-claude-gradient",
    "name": "html-ppt-obsidian-claude-gradient",
    "description": "| OpenDesign's enterprise AI-adoption brief: local-first agents at work, the risk controls, the ROI, and the rollout plan. Built as a decision-grade AI literacy deck for leadership, IT, security. en_d",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"enterprise-ai-copilot-rollout-brief\"",
      "\"ai-literacy\"",
      "\"Write an Enterprise AI Adoption Brief like a Transformation Lead\"",
      "\"像企业 AI 转型负责人一样写落地简报\"",
      "\"ai\"",
      "\"copilot\"",
      "\"workflow\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-pitch-deck",
    "name": "html-ppt-pitch-deck",
    "description": "| OpenDesign's demo-day pitch: hook, traction, moat, and the raise — built to make a partner sit up by page three. Built as a decision-grade fundraising pitch deck for accelerator partners, angels. en",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"series-a-pitch-deck\"",
      "\"fundraising-pitch\"",
      "\"Write a Demo Day Pitch like a Top Accelerator Partner\"",
      "\"像顶级加速器合伙人一样写 Demo Day 路演\"",
      "\"pitch-deck\"",
      "\"fundraising\"",
      "\"investor-deck\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-presenter-mode-reveal",
    "name": "html-ppt-presenter-mode",
    "description": "| OpenDesign live demo: from a one-line prompt to runnable design in a single session — the flow, live. Built as a decision-grade AI literacy deck for developers, prospects, community. en_description:",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"enterprise-ai-copilot-rollout-brief\"",
      "\"ai-literacy\"",
      "\"Run a Live AI Product Demo like a Founding DevRel Lead\"",
      "\"像创始 DevRel 一样做现场 AI 演示\"",
      "\"ai\"",
      "\"copilot\"",
      "\"workflow\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-product-launch",
    "name": "html-ppt-product-launch",
    "description": "| OpenDesign Teams: a launch-and-adoption proposal for a mid-market design team weighing a switch from closed cloud tools. Built as a decision-grade B2B sales deck for design team lead, IT. en_descrip",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"b2b-saas-sales-proposal\"",
      "\"b2b-sales\"",
      "\"Pitch a Team Rollout like a Strategic Account Executive\"",
      "\"像战略客户 AE 一样推动团队落地\"",
      "\"sales\"",
      "\"renewal\"",
      "\"customer\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-taste-brutalist",
    "name": "html-ppt-taste-brutalist",
    "description": "16:9 HTML deck in tactical-telemetry / CRT-terminal taste. Deactivated-CRT charcoal slides, white-phosphor monospace, hazard-red accent, scanline overlay, ASCII syntax, density over decoration. Distil",
    "mode": "prototype",
    "tags": []
  },
  {
    "id": "html-ppt-taste-editorial",
    "name": "html-ppt-taste-editorial",
    "description": "16:9 HTML deck in editorial-minimalist taste. Warm cream slides, serif display + grotesque body, hairline rules, monospace meta, generous macro-whitespace, one accent. Distilled from Leonxlnx/taste-sk",
    "mode": "prototype",
    "tags": []
  },
  {
    "id": "html-ppt-tech-sharing",
    "name": "html-ppt-tech-sharing",
    "description": "| OpenDesign internals: how the agent stream, sandbox, and artifacts work — an engineering deep-dive talk. Built as a decision-grade AI literacy deck for engineers, dev community. en_description: | Op",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"enterprise-ai-copilot-rollout-brief\"",
      "\"ai-literacy\"",
      "\"Give an Engineering Tech Talk like a Staff Developer-Advocate\"",
      "\"像 Staff DevRel 一样做工程分享\"",
      "\"ai\"",
      "\"copilot\"",
      "\"workflow\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-testing-safety-alert",
    "name": "html-ppt-testing-safety-alert",
    "description": "| A hospital data-governance briefing: patient-data risk, the control framework, accountability, and the approval the board must give. Built as a decision-grade policy briefing deck for health-system ",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"policy-briefing-deck\"",
      "\"government-policy\"",
      "\"Brief a Health-System Board on Data Governance like a Chief Compliance Officer\"",
      "\"像首席合规官一样向医院董事会汇报数据治理\"",
      "\"policy\"",
      "\"regulatory\"",
      "\"risk-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-weekly-report",
    "name": "html-ppt-weekly-report",
    "description": "| OpenDesign's weekly growth review: stars, installs, activation — the number, the driver, and the recommended move. Built as a decision-grade data & finance deck for growth & product team. en_descrip",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"product-analytics-deck\"",
      "\"data-finance\"",
      "\"Write a Weekly Growth Review like a Head of Analytics\"",
      "\"像分析负责人一样写每周增长复盘\"",
      "\"kpi\"",
      "\"finance\"",
      "\"metrics\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-xhs-pastel-card",
    "name": "html-ppt-xhs-pastel-card",
    "description": "| A personal manifesto: a year of saying yes — the premise, the scenes, the turn, and the meaning that lands. Built as a decision-grade story deck for community, talk audience. en_description: | A per",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"travel-photo-essay-deck\"",
      "\"life\"",
      "\"Write a Personal Manifesto Talk like a Narrative Podcast Producer\"",
      "\"像叙事播客制作人一样写个人宣言演讲\"",
      "\"story\"",
      "\"personal\"",
      "\"photo-essay\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-xhs-white-editorial",
    "name": "html-ppt-xhs-white-editorial",
    "description": "| A staff-engineer promotion packet — scope, the proof moments, the artifacts, and the impact that clears the bar. Built as a decision-grade career deck for manager, calibration committee. en_descript",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"year-end-self-review-deck\"",
      "\"career\"",
      "\"Write a Staff-Engineer Promotion Case like a Calibration-Committee Insider\"",
      "\"像晋升评审内部人一样写 Staff 工程师晋升材料\"",
      "\"portfolio\"",
      "\"promotion\"",
      "\"self-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/lewislulu/html-ppt-skill\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-8-bit-orbit",
    "name": "8-Bit Orbit",
    "description": "| A gamer's journey building a retro-arcade collection — the obsession, the hunt, and what the machines came to mean. Built as a decision-grade story deck for friends, hobby community. en_description:",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"travel-photo-essay-deck\"",
      "\"life\"",
      "\"Turn a Hobby into a Story Deck like a Passion-Project Storyteller\"",
      "\"像热爱驱动的讲述者一样把爱好做成故事\"",
      "\"story\"",
      "\"personal\"",
      "\"photo-essay\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/8-bit-orbit\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-biennale-yellow",
    "name": "Biennale Yellow",
    "description": "| A curatorial deck for a contemporary art biennale — the thesis, the rooms, the works, and the visitor journey. Built as a decision-grade design craft deck for museum board, curators. en_description:",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-upgrade-deck-rescue\"",
      "\"design-craft\"",
      "\"Curate an Art Biennale Deck like a Museum Exhibition Director\"",
      "\"像美术馆策展总监一样做双年展策展稿\"",
      "\"design\"",
      "\"brand\"",
      "\"visual-system\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/biennale-yellow\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-block-frame",
    "name": "BlockFrame",
    "description": "| Rescuing a messy startup deck into a board-grade system — the diagnosis, the page grammar, and the rebuilt proof pages. Built as a decision-grade design craft deck for founders, exec presenter. en_d",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-upgrade-deck-rescue\"",
      "\"design-craft\"",
      "\"Rescue a Messy Deck to Board-Grade like an Executive Design Director\"",
      "\"像高管级设计总监一样把混乱 Deck 救到董事会级\"",
      "\"design\"",
      "\"brand\"",
      "\"visual-system\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/block-frame\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-blue-professional",
    "name": "Blue Professional",
    "description": "| OpenDesign's QBR for the executive committee: what moved, what stalled, and the resource reallocation ask. Built as a decision-grade corporate strategy deck for executive committee. en_description: ",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-pre-read-deck\"",
      "\"corporate-strategy\"",
      "\"Present a Quarterly Business Review like a Chief of Staff\"",
      "\"像幕僚长一样做季度经营回顾\"",
      "\"board\"",
      "\"strategy\"",
      "\"business-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/blue-professional\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-bold-poster",
    "name": "Bold Poster",
    "description": "| OpenDesign's Series A growth story: the traction curve, the expansion motion, and why it's venture-scale. Built as a decision-grade fundraising pitch deck for Series A partners. en_description: | Op",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"series-a-pitch-deck\"",
      "\"fundraising-pitch\"",
      "\"Write a Series A Growth Story like a Tier-1 VC Partner\"",
      "\"像一线 VC 合伙人一样写 A 轮增长叙事\"",
      "\"pitch-deck\"",
      "\"fundraising\"",
      "\"investor-deck\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/bold-poster\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-broadside",
    "name": "Broadside",
    "description": "| OpenDesign's product-launch announcement and press narrative — the headline, the proof points, and the call to action. Built as a decision-grade marketing & GTM deck for press, community, prospects.",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"annual-marketing-plan\"",
      "\"marketing-gtm\"",
      "\"Write a Product-Launch Announcement like a PR & Comms Director\"",
      "\"像公关传播总监一样写产品发布公告\"",
      "\"launch\"",
      "\"campaign\"",
      "\"pipeline\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/broadside\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-capsule",
    "name": "Capsule",
    "description": "| A year-end self-review for a product manager — the role, the outcomes, the learning, and the ask, all evidence-backed. Built as a decision-grade career deck for manager, review committee. en_descrip",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"year-end-self-review-deck\"",
      "\"career\"",
      "\"Write a Year-End Self-Review like a Promotion-Committee Insider\"",
      "\"像晋升委员会内部人一样写年终述职\"",
      "\"portfolio\"",
      "\"promotion\"",
      "\"self-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/capsule\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-cartesian",
    "name": "Cartesian",
    "description": "| An economics senior thesis on the employment effects of local minimum-wage increases — identification strategy, evidence, and limitations. Built as a decision-grade coursework defense deck for thesi",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"senior-capstone-defense-deck\"",
      "\"student-coursework\"",
      "\"Present a Senior Thesis Defense like a Distinction-Grade Economics Student\"",
      "\"像拿优等的经济学生一样做毕业论文答辩\"",
      "\"coursework\"",
      "\"defense\"",
      "\"academic\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/cartesian\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-cobalt-grid",
    "name": "Cobalt Grid",
    "description": "| OpenDesign renewal + seat-expansion business case for a growing customer: realized value, usage proof, and the expansion ROI. Built as a decision-grade B2B sales deck for champion, finance approver.",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"b2b-saas-sales-proposal\"",
      "\"b2b-sales\"",
      "\"Write a Renewal & Expansion Business Case like an Account Director\"",
      "\"像客户总监一样写续约与扩容论证\"",
      "\"sales\"",
      "\"renewal\"",
      "\"customer\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/cobalt-grid\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-coral",
    "name": "Coral",
    "description": "| OpenDesign's community-growth campaign across GitHub, Discord, and X: the loops, the content calendar, and the pipeline math. Built as a decision-grade marketing & GTM deck for growth team, communit",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"annual-marketing-plan\"",
      "\"marketing-gtm\"",
      "\"Plan a Community-Growth Campaign like a Head of Growth\"",
      "\"像增长负责人一样规划社区增长战役\"",
      "\"launch\"",
      "\"campaign\"",
      "\"pipeline\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/coral\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-creative-mode",
    "name": "Creative Mode",
    "description": "| A brand visual-identity system reveal for an outdoor label — logo, color, type, and the rules that keep it consistent. Built as a decision-grade design craft deck for brand team, client. en_descript",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-upgrade-deck-rescue\"",
      "\"design-craft\"",
      "\"Present a Visual-Identity System like a Lead Brand Designer\"",
      "\"像主创品牌设计师一样发布视觉识别系统\"",
      "\"design\"",
      "\"brand\"",
      "\"visual-system\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/creative-mode\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-daisy-days",
    "name": "Daisy Days",
    "description": "| A customer-success workshop onboarding users to a project-management app — the first-value path and the habits that retain. Built as a decision-grade professional training deck for new customers, CS",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"employee-onboarding-deck\"",
      "\"professional-training\"",
      "\"Write a Customer Onboarding Workshop like a Field Enablement Director\"",
      "\"像客户成功赋能总监一样写客户上手工作坊\"",
      "\"training-deck\"",
      "\"workshop\"",
      "\"course-module\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/daisy-days\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-editorial-tri-tone",
    "name": "Editorial Tri-Tone",
    "description": "| A type-and-color system for a culture magazine relaunch — the grid, the tri-tone palette, and the layout kit. Built as a decision-grade design craft deck for editorial & design team. en_description:",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-upgrade-deck-rescue\"",
      "\"design-craft\"",
      "\"Build an Editorial Design System like a Magazine Art Director\"",
      "\"像杂志艺术总监一样搭建编辑设计系统\"",
      "\"design\"",
      "\"brand\"",
      "\"visual-system\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/editorial-tri-tone\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-grove",
    "name": "Grove",
    "description": "| A municipal urban-tree-canopy policy proposal — the public need, the evidence, the options, and the funding decision. Built as a decision-grade policy briefing deck for city council, agency reviewer",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"policy-briefing-deck\"",
      "\"government-policy\"",
      "\"Write an Urban Green-Space Policy Brief like a City Sustainability Director\"",
      "\"像城市可持续总监一样写城市绿地政策简报\"",
      "\"policy\"",
      "\"regulatory\"",
      "\"risk-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/grove\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-long-table",
    "name": "Long Table",
    "description": "| OpenDesign's unit-economics and BYOK cost model: the assumptions, the sensitivity, and why it scales. Built as a decision-grade data & finance deck for CFO, investors. en_description: | OpenDesign's",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"product-analytics-deck\"",
      "\"data-finance\"",
      "\"Present a Unit-Economics Model like an FP&A Partner\"",
      "\"像 FP&A 伙伴一样讲清单位经济模型\"",
      "\"kpi\"",
      "\"finance\"",
      "\"metrics\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/long-table\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-mat",
    "name": "Mat",
    "description": "| A margin-recovery diagnosis for a regional grocery chain — the governing thought, the driver tree, the priorities, and the roadmap. Built as a decision-grade consulting deck for client sponsor, stee",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"consulting-final-deck\"",
      "\"consulting\"",
      "\"Write a Margin-Recovery Final Deck like a McKinsey Engagement Manager\"",
      "\"像麦肯锡项目经理一样写利润率修复终稿\"",
      "\"consulting-deliverable\"",
      "\"strategy\"",
      "\"client\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/mat\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-monochrome",
    "name": "Monochrome",
    "description": "| A grant proposal on CRISPR base-editing for sickle-cell disease — the hypothesis, the approach, the milestones, and the risk. Built as a decision-grade academic research deck for grant review commit",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"academic-review-deck\"",
      "\"academic-research\"",
      "\"Write a Grant Committee Brief like a Funded Principal Investigator\"",
      "\"像拿到资助的 PI 一样写基金评审简报\"",
      "\"research\"",
      "\"grant\"",
      "\"review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/monochrome\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-neo-grid-bold",
    "name": "Neo-Grid Bold",
    "description": "| A designer's portfolio narrative for a senior interview — three case studies, the craft, and the judgment behind each. Built as a decision-grade career deck for hiring panel. en_description: | A des",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"year-end-self-review-deck\"",
      "\"career\"",
      "\"Build a Designer Portfolio Narrative like a Hiring Bar-Raiser\"",
      "\"像招聘 Bar Raiser 一样搭设计作品集叙事\"",
      "\"portfolio\"",
      "\"promotion\"",
      "\"self-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/neo-grid-bold\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-peoples-platform",
    "name": "People's Platform (Block & Bold)",
    "description": "| A public-transit funding proposal for a city council — ridership need, the plan, the risk controls, and the ask. Built as a decision-grade policy briefing deck for city council, public board. en_des",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"policy-briefing-deck\"",
      "\"government-policy\"",
      "\"Make a Public-Transit Funding Case like a Transportation Policy Lead\"",
      "\"像交通政策负责人一样做公共交通投资论证\"",
      "\"policy\"",
      "\"regulatory\"",
      "\"risk-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/peoples-platform\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-pin-and-paper",
    "name": "Pin & Paper",
    "description": "| A field-biology capstone on urban pollinator decline — the survey design, the data, the contribution, and the caveats. Built as a decision-grade coursework defense deck for faculty reviewers. en_des",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"senior-capstone-defense-deck\"",
      "\"student-coursework\"",
      "\"Turn a Field-Study Capstone into a Defense Deck like a Star Biology Major\"",
      "\"像明星生物学生一样做田野调查答辩\"",
      "\"coursework\"",
      "\"defense\"",
      "\"academic\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/pin-and-paper\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-pink-script",
    "name": "Pink Script — After Hours",
    "description": "| A wedding-anniversary tribute photo essay — a decade in scenes, the turning points, and the quiet meaning of staying. Built as a decision-grade story deck for couple, family, friends. en_description",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"travel-photo-essay-deck\"",
      "\"life\"",
      "\"Turn an Anniversary into a Photo Essay like a Wedding Storyteller\"",
      "\"像婚礼讲述者一样把纪念日做成影像散文\"",
      "\"story\"",
      "\"personal\"",
      "\"photo-essay\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/pink-script\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-playful",
    "name": "Playful",
    "description": "| A retail sales-floor training on consultative selling — the flow, the role-plays, and the daily habit that lifts conversion. Built as a decision-grade professional training deck for store associates",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"employee-onboarding-deck\"",
      "\"professional-training\"",
      "\"Run a Sales-Floor Training like a Top Retail Coach\"",
      "\"像顶级零售教练一样做门店销售培训\"",
      "\"training-deck\"",
      "\"workshop\"",
      "\"course-module\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/playful\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-raw-grid",
    "name": "Raw Grid",
    "description": "| A brutalist poster-series case study for a music festival — the concept, the system, and how it scaled across formats. Built as a decision-grade design craft deck for design peers, client. en_descri",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-upgrade-deck-rescue\"",
      "\"design-craft\"",
      "\"Present a Poster-Series Case Study like a Festival Art Director\"",
      "\"像音乐节艺术总监一样讲海报系列案例\"",
      "\"design\"",
      "\"brand\"",
      "\"visual-system\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/raw-grid\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-retro-windows",
    "name": "Retro Windows",
    "description": "| An IT security-awareness training on spotting phishing — the tells, the drill, and what to do in the first 60 seconds. Built as a decision-grade professional training deck for all employees. en_desc",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"employee-onboarding-deck\"",
      "\"professional-training\"",
      "\"Deliver a Security-Awareness Training like a CISO Enablement Team\"",
      "\"像 CISO 赋能团队一样做安全意识培训\"",
      "\"training-deck\"",
      "\"workshop\"",
      "\"course-module\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/retro-windows\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-retro-zine",
    "name": "Retro Zine",
    "description": "| A neighborhood zine on the disappearing corner shops — portraits, voices, and what a block loses when they close. Built as a decision-grade story deck for community, local readers. en_description: |",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"travel-photo-essay-deck\"",
      "\"life\"",
      "\"Make a Neighborhood Zine Story like an Indie Photo Editor\"",
      "\"像独立图片编辑一样做街区 zine 故事\"",
      "\"story\"",
      "\"personal\"",
      "\"photo-essay\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/retro-zine\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-sakura-chroma",
    "name": "Sakura Chroma",
    "description": "| A cherry-blossom-season travel photo essay through Kyoto — the arrival, the peak bloom, and the moment that made the trip. Built as a decision-grade story deck for friends, travel readers. en_descri",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"travel-photo-essay-deck\"",
      "\"life\"",
      "\"Turn a Cherry-Blossom Trip into a Photo Essay like a Travel Editorial Director\"",
      "\"像旅行内容总监一样把樱花之旅做成影像散文\"",
      "\"story\"",
      "\"personal\"",
      "\"photo-essay\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/sakura-chroma\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-scatterbrain",
    "name": "Scatterbrain",
    "description": "| A design-school graduation project: a civic wayfinding system for a transit hub — the brief, the process, and the outcome. Built as a decision-grade coursework defense deck for crit panel, faculty. ",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"senior-capstone-defense-deck\"",
      "\"student-coursework\"",
      "\"Pitch a Graduation Design Project like a Portfolio-Ready Design Student\"",
      "\"像作品集出众的设计学生一样讲毕业设计\"",
      "\"coursework\"",
      "\"defense\"",
      "\"academic\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/scatterbrain\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-signal",
    "name": "Signal",
    "description": "| OpenDesign's strategy memo: should it monetize the plugin registry now or hold — options, risks, and the recommendation. Built as a decision-grade corporate strategy deck for CEO, strategy team. en_",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-pre-read-deck\"",
      "\"corporate-strategy\"",
      "\"Write a Strategy Decision Memo like a Corp-Dev Lead\"",
      "\"像战略发展负责人一样写战略决策备忘\"",
      "\"board\"",
      "\"strategy\"",
      "\"business-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/signal\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-soft-editorial",
    "name": "Soft Editorial",
    "description": "| A digital-transformation roadmap for a legacy insurer — the diagnosis, the sequenced bets, and the operating rhythm to land them. Built as a decision-grade consulting deck for client executives. en_",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"consulting-final-deck\"",
      "\"consulting\"",
      "\"Deliver a Digital-Transformation Roadmap like a Big-Four Partner\"",
      "\"像四大合伙人一样交付数字化转型路线图\"",
      "\"consulting-deliverable\"",
      "\"strategy\"",
      "\"client\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/soft-editorial\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-stencil-tablet",
    "name": "Stencil & Tablet",
    "description": "| A workplace-safety compliance review for a manufacturing regulator — findings, the evidence chain, and the corrective mandate. Built as a decision-grade policy briefing deck for regulator, plant lea",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"policy-briefing-deck\"",
      "\"government-policy\"",
      "\"Present a Workplace-Safety Compliance Review like a Senior Regulator\"",
      "\"像资深监管者一样做工作场所安全合规评审\"",
      "\"policy\"",
      "\"regulatory\"",
      "\"risk-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/stencil-tablet\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-studio",
    "name": "Studio",
    "description": "| A photography studio's portfolio-and-rate deck — the signature work, the process, and the packages that win the brief. Built as a decision-grade design craft deck for prospective clients. en_descrip",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-upgrade-deck-rescue\"",
      "\"design-craft\"",
      "\"Build a Studio Portfolio & Rate Deck like a Creative Studio Owner\"",
      "\"像创意工作室主理人一样做作品与报价稿\"",
      "\"design\"",
      "\"brand\"",
      "\"visual-system\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/studio\""
    ]
  },
  {
    "id": "html-ppt-zhangzara-vellum",
    "name": "Vellum",
    "description": "| A humanities lecture: how Renaissance linear perspective reshaped early cartography — sources, argument, and evidence. Built as a decision-grade academic research deck for faculty, graduate seminar.",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"academic-review-deck\"",
      "\"academic-research\"",
      "\"Deliver a Humanities Research Lecture like a Tenured Art Historian\"",
      "\"像终身教授一样做人文研究讲座\"",
      "\"research\"",
      "\"grant\"",
      "\"review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/zarazhangrui/beautiful-html-templates/tree/main/templates/vellum\""
    ]
  },
  {
    "id": "hyperframes",
    "name": "hyperframes",
    "description": "Create video compositions, animations, title cards, overlays, captions, voiceovers, audio-reactive visuals, and scene transitions in HyperFrames HTML. Use when asked to build any HTML-based video cont",
    "mode": "video",
    "tags": [],
    "triggers": [
      "\"hyperframes\"",
      "\"html video\"",
      "\"video composition\"",
      "\"interactive video\"",
      "\"captions\"",
      "\"tts video\"",
      "\"kinetic typography\"",
      "\"html in canvas\"",
      "\"drawElementImage\"",
      "\"html shader\"",
      "\"vfx-iphone-device\"",
      "\"vfx-liquid-glass\""
    ]
  },
  {
    "id": "ib-pitch-book",
    "name": "ib-pitch-book",
    "description": "| OpenDesign's investor pitch book: market map, moat, unit economics, and the ask — analyst-grade and diligence-ready. Built as a decision-grade fundraising pitch deck for growth-equity investors. en_",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"series-a-pitch-deck\"",
      "\"fundraising-pitch\"",
      "\"Write an Investor Pitch Book like a Growth-Equity Analyst\"",
      "\"像成长股权分析师一样写投资 Pitch Book\"",
      "\"pitch-deck\"",
      "\"fundraising\"",
      "\"investor-deck\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "upstream: \"https://github.com/anthropics/financial-services/tree/main/plugins/agent-plugins/pitch-agent\""
    ]
  },
  {
    "id": "image-poster",
    "name": "image-poster",
    "description": "| Single-image generation skill for posters, key art, and editorial illustrations. Defaults to gpt-image-2 but is provider-agnostic — the same workflow drives Flux, Imagen, or Midjourney via the activ",
    "mode": "image",
    "tags": [],
    "triggers": [
      "\"poster\"",
      "\"key art\"",
      "\"illustration\"",
      "\"image\"",
      "\"cover art\"",
      "\"海报\"",
      "\"插画\"",
      "od:",
      "mode: image",
      "surface: image",
      "scenario: design",
      "preview:"
    ]
  },
  {
    "id": "invoice",
    "name": "invoice",
    "description": "| A printable invoice page — sender + recipient block, line items table, tax breakdown, totals, and payment instructions. Use when the brief mentions \"invoice\", \"bill\", \"billing statement\", or \"发票\". t",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"invoice\"",
      "\"bill\"",
      "\"billing statement\"",
      "\"发票\"",
      "\"账单\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: finance",
      "preview:",
      "type: html",
      "entry: index.html"
    ]
  },
  {
    "id": "kami-deck",
    "name": "kami-deck",
    "description": "| A lab-meeting deck on gut-microbiome links to sleep quality — the design, the results, the caveats, and the next experiment. Built as a decision-grade academic research deck for lab group, PI. en_de",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"academic-review-deck\"",
      "\"academic-research\"",
      "\"Turn a Study into a Lab Meeting Deck like a Senior Postdoc\"",
      "\"像资深博士后一样做组会研究汇报\"",
      "\"research\"",
      "\"grant\"",
      "\"review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "surface: web",
      "mode: deck"
    ]
  },
  {
    "id": "kami-landing",
    "name": "kami-landing",
    "description": "> Produce a print-grade single-page kami (紙 / 纸) document — warm parchment canvas, ink-blue accent, serif at one weight, no italic, no cool grays. The output reads like a professional white paper or s",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "kami",
      "紙",
      "纸",
      "paper one-pager",
      "白皮书",
      "white paper",
      "parchment landing",
      "editorial document",
      "print-grade page",
      "kami landing",
      "od:",
      "category: brand-page"
    ]
  },
  {
    "id": "kanban-board",
    "name": "kanban-board",
    "description": "| Kanban / task board with columns (To do / In progress / In review / Done), draggable-looking cards, assignee avatars, swimlanes, and a top filter bar. Use when the brief mentions \"kanban\", \"task boa",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"kanban\"",
      "\"task board\"",
      "\"sprint board\"",
      "\"trello\"",
      "\"jira board\"",
      "\"看板\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: operations",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "last30days",
    "name": "last30days",
    "description": "| Recent community and social trend research over the last 30 days. Use when the brief asks what people are saying now, recent sentiment, community reactions, social proof, launch reaction, trend scan",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"last 30 days\"",
      "\"last30days\"",
      "\"recent sentiment\"",
      "\"community reaction\"",
      "\"what people are saying\"",
      "\"trend scan\"",
      "\"social research\"",
      "\"最近30天\"",
      "\"社区反馈\"",
      "od:",
      "mode: prototype",
      "preview:"
    ]
  },
  {
    "id": "live-artifact",
    "name": "live-artifact",
    "description": "| Create refreshable, auditable OpenDesign artifacts backed by connector or local data. Trigger when the user asks for live dashboards, refreshable reports, synced views, or reusable data-backed artif",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"live artifact\"",
      "\"live dashboard\"",
      "\"refreshable dashboard\"",
      "\"live report\"",
      "\"refreshable report\"",
      "\"synced view\"",
      "\"可刷新\"",
      "\"实时看板\"",
      "od:",
      "mode: prototype",
      "scenario: live",
      "preview:"
    ]
  },
  {
    "id": "live-dashboard",
    "name": "live-dashboard",
    "description": "| Notion-style team dashboard rendered as a Live Artifact. A single-page, self-contained HTML dashboard with KPIs, a 7-day sparkline, a real-time activity feed and a linked-database task table — wired",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"team dashboard\"",
      "\"notion dashboard\"",
      "\"live dashboard\"",
      "\"ops dashboard\"",
      "\"team workspace dashboard\"",
      "\"团队仪表盘\"",
      "\"Notion 仪表盘\"",
      "\"Live Artifact dashboard\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: operation"
    ]
  },
  {
    "id": "magazine-poster",
    "name": "magazine-poster",
    "description": "| An editorial-style poster — newsprint paper, dateline, oversized serif headline with a struck-through word and italic accent, a 2-column body block, and 6 numbered sections with annotated pull-quote",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"magazine poster\"",
      "\"editorial poster\"",
      "\"newsprint\"",
      "\"newspaper layout\"",
      "\"essay\"",
      "\"manifesto\"",
      "\"long-form poster\"",
      "\"杂志海报\"",
      "\"报纸版式\"",
      "od:",
      "featured: 0.02",
      "mode: prototype"
    ]
  },
  {
    "id": "meeting-notes",
    "name": "meeting-notes",
    "description": "| Meeting notes page — title bar with attendees, agenda checklist, decisions block, action items table with owners + dates, and a \"next meeting\" footer. Use when the brief mentions \"meeting notes\", \"m",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"meeting notes\"",
      "\"minutes\"",
      "\"1:1 notes\"",
      "\"all-hands recap\"",
      "\"会议纪要\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: operations",
      "preview:",
      "type: html",
      "entry: index.html"
    ]
  },
  {
    "id": "mobile-app",
    "name": "mobile-app",
    "description": "| A mobile-app screen rendered inside a pixel-accurate iPhone 15 Pro frame on the page. Built by copying the seed `assets/template.html` and pasting one screen archetype from `references/layouts.md`. ",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"mobile app\"",
      "\"ios app\"",
      "\"android app\"",
      "\"phone screen\"",
      "\"app ui\"",
      "\"app mockup\"",
      "\"移动端\"",
      "\"手机 app\"",
      "od:",
      "mode: prototype",
      "platform: mobile",
      "scenario: design"
    ]
  },
  {
    "id": "mobile-onboarding",
    "name": "mobile-onboarding",
    "description": "| A multi-screen mobile onboarding flow rendered as three phone frames side by side — splash, value-prop, sign-in. Status bar, swipe dots, primary CTA. Use when the brief mentions \"mobile onboarding\",",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"mobile onboarding\"",
      "\"ios onboarding\"",
      "\"android onboarding\"",
      "\"phone signup\"",
      "\"app onboarding\"",
      "\"移动端引导\"",
      "od:",
      "mode: prototype",
      "platform: mobile",
      "scenario: design",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "motion-frames",
    "name": "motion-frames",
    "description": "| A single-frame motion-design composition with looping CSS animations — rotating type ring, animated globe, ticking timer, parallax labels. Renders as a hero video poster you can hand straight to Hyp",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"motion design\"",
      "\"motion graphic\"",
      "\"animated hero\"",
      "\"loop animation\"",
      "\"video poster\"",
      "\"title card\"",
      "\"hyperframes\"",
      "\"kinetic typography\"",
      "\"动态设计\"",
      "\"动效\"",
      "od:",
      "mode: prototype"
    ]
  },
  {
    "id": "open-design-landing",
    "name": "open-design-landing",
    "description": "> Produce a world-class single-page editorial landing site in the Atelier Zero visual language (Monocle / Apartamento / Études editorial collage) — the same aesthetic OpenDesign uses for its own marke",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "landing page",
      "落地页",
      "editorial site",
      "magazine layout",
      "hero collage",
      "atelier zero",
      "open design landing",
      "od:",
      "category: brand-page",
      "surface: web",
      "scenario: marketing",
      "audience: founders, design studios, OSS maintainers"
    ]
  },
  {
    "id": "open-design-landing-deck",
    "name": "open-design-landing-deck",
    "description": "| OpenDesign's brand-story deck for partners and press: why it exists, what it believes, and where design is going. Built as a decision-grade marketing & GTM deck for partners, press, community. en_de",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"annual-marketing-plan\"",
      "\"marketing-gtm\"",
      "\"Write a Brand-Story Deck like a Founder Storyteller\"",
      "\"像会讲故事的创始人一样写品牌故事稿\"",
      "\"launch\"",
      "\"campaign\"",
      "\"pipeline\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "surface: web",
      "mode: deck"
    ]
  },
  {
    "id": "orbit-general",
    "name": "orbit-general",
    "description": "| Open Orbit briefing skill — selected by the Orbit pipeline when the user has two or more connectors connected. Pulls the past 24 hours of activity from every authenticated connector (GitHub, Linear,",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"orbit\"",
      "\"daily digest\"",
      "\"morning briefing\"",
      "\"每日简报\"",
      "\"早安简报\"",
      "\"跨工具汇总\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: orbit",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "orbit-github",
    "name": "orbit-github",
    "description": "| Open Orbit briefing skill — selected by the Orbit pipeline when GitHub is the user's only connected connector, or when the user explicitly scopes their daily digest to GitHub. Pulls the past 24 hour",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"github briefing\"",
      "\"github digest\"",
      "\"pr digest\"",
      "\"github 简报\"",
      "\"代码活动汇总\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: orbit",
      "preview:",
      "type: html",
      "entry: index.html"
    ]
  },
  {
    "id": "orbit-gmail",
    "name": "orbit-gmail",
    "description": "| Open Orbit briefing skill — selected by the Orbit pipeline when Gmail is the user's only connected connector, or when the user explicitly scopes their daily digest to Gmail. Pulls the past 24 hours ",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"gmail briefing\"",
      "\"inbox digest\"",
      "\"email summary\"",
      "\"gmail 简报\"",
      "\"邮件摘要\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: orbit",
      "preview:",
      "type: html",
      "entry: index.html"
    ]
  },
  {
    "id": "orbit-linear",
    "name": "orbit-linear",
    "description": "| Open Orbit briefing skill — selected by the Orbit pipeline when Linear is the user's only connected connector, or when the user explicitly scopes their daily digest to Linear. Pulls the past 24 hour",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"linear briefing\"",
      "\"linear digest\"",
      "\"issue digest\"",
      "\"linear 简报\"",
      "\"issue 汇总\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: orbit",
      "preview:",
      "type: html",
      "entry: index.html"
    ]
  },
  {
    "id": "orbit-notion",
    "name": "orbit-notion",
    "description": "| Open Orbit briefing skill — selected by the Orbit pipeline when Notion is the user's only connected connector, or when the user explicitly scopes their daily digest to Notion. Pulls the past 24 hour",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"notion briefing\"",
      "\"notion digest\"",
      "\"doc digest\"",
      "\"notion 简报\"",
      "\"文档摘要\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: orbit",
      "preview:",
      "type: html",
      "entry: index.html"
    ]
  },
  {
    "id": "pm-spec",
    "name": "pm-spec",
    "description": "| Product spec / PRD as a single page — problem, success metrics, scope, user stories, design notes, rollout plan, open questions. Use when the brief mentions \"PRD\", \"spec\", \"product spec\", \"feature b",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"prd\"",
      "\"spec\"",
      "\"product spec\"",
      "\"feature brief\"",
      "\"feature doc\"",
      "\"需求文档\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: product",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "pricing-page",
    "name": "pricing-page",
    "description": "| A standalone pricing page — header, plan tiers, feature comparison table, and an FAQ. Use when the brief asks for \"pricing\", \"plans\", \"subscription tiers\", or a \"compare plans\" page. triggers: - \"pr",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"pricing\"",
      "\"pricing page\"",
      "\"plans\"",
      "\"subscription\"",
      "\"compare plans\"",
      "\"定价\"",
      "\"套餐\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: sales",
      "preview:"
    ]
  },
  {
    "id": "replit-deck",
    "name": "replit-deck",
    "description": "| For product and technical management work: turn PRDs, roadmaps, RFCs, architecture reviews, and retros into decision documents. Built around the core query \"pm-feature-business-case-deck\", with prod",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"pm-feature-business-case-deck\"",
      "\"product-management\"",
      "\"Write a Feature Business Case like a Principal PM\"",
      "\"像 Principal PM 一样写功能商业论证\"",
      "\"product\"",
      "\"roadmap\"",
      "\"architecture\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "preview:"
    ]
  },
  {
    "id": "saas-landing",
    "name": "saas-landing",
    "description": "| Single-page SaaS landing with hero, features, social proof, pricing, and CTA. Respects the active DESIGN.md color/typography/layout tokens. Trigger keywords: \"saas landing\", \"marketing page\", \"produ",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"saas landing\"",
      "\"marketing page\"",
      "\"product landing\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: marketing",
      "preview:",
      "type: html",
      "entry: index.html",
      "reload: debounce-100",
      "design_system:"
    ]
  },
  {
    "id": "simple-deck",
    "name": "simple-deck",
    "description": "| OpenDesign's operating review: growth, burn, and the concrete path to sustainability without losing the open ethos. Built as a decision-grade corporate strategy deck for leadership team. en_descript",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"board-pre-read-deck\"",
      "\"corporate-strategy\"",
      "\"Write an Operating Review like a Disciplined COO\"",
      "\"像克制的 COO 一样写经营复盘\"",
      "\"board\"",
      "\"strategy\"",
      "\"business-review\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "preview:"
    ]
  },
  {
    "id": "social-carousel",
    "name": "social-carousel",
    "description": "| A three-card social-media carousel laid out as 1080×1080 squares — three cinematic, on-brand panels with display headlines that connect across the series (\"onwards.\" → \"to the next one.\" → \"looking ",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"social carousel\"",
      "\"carousel post\"",
      "\"instagram carousel\"",
      "\"linkedin carousel\"",
      "\"x thread cards\"",
      "\"social series\"",
      "\"三连发\"",
      "\"轮播图\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: marketing"
    ]
  },
  {
    "id": "social-media-dashboard",
    "name": "social-media-dashboard",
    "description": "| Creator-facing social media analytics dashboard in a single HTML file. A platform switcher (X / LinkedIn / YouTube / Instagram), a row of KPI cards (followers, engagement rate, likes, reposts), a fo",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"social media dashboard\"",
      "\"social analytics\"",
      "\"creator dashboard\"",
      "\"creator analytics\"",
      "\"social media analytics\"",
      "\"社媒后台\"",
      "\"创作者后台\"",
      "\"社交媒体仪表盘\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: creator"
    ]
  },
  {
    "id": "social-media-matrix-tracker-template",
    "name": "social-media-matrix-tracker-template",
    "description": "| 社媒矩阵数据追踪面板模板（Social Media Matrix Tracker）。 Use when users ask for a cinematic, data-dense social media analytics dashboard with multi-platform metrics, interactive charts, hover insights, range comp",
    "mode": "template",
    "tags": [],
    "triggers": [
      "\"social media matrix tracker\"",
      "\"social media dashboard template\"",
      "\"creator analytics template\"",
      "\"live social dashboard\"",
      "\"social analytics\"",
      "\"content performance\"",
      "\"TikTok analytics dashboard\"",
      "\"Instagram analytics dashboard\"",
      "\"YouTube analytics dashboard\"",
      "\"multi-platform creator dashboard\"",
      "\"社媒矩阵数据追踪面板\"",
      "\"社媒矩阵看板模板\""
    ]
  },
  {
    "id": "sprite-animation",
    "name": "sprite-animation",
    "description": "| A pixel / sprite-style animated explainer slide — full-bleed cream stage, bold display year, animated pixel-art mascot (e.g. Hanafuda card, mushroom, or 8-bit console), kinetic Japanese display type",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"sprite animation\"",
      "\"pixel art animation\"",
      "\"8-bit explainer\"",
      "\"retro animation\"",
      "\"kinetic typography\"",
      "\"history explainer\"",
      "\"nintendo style\"",
      "\"精灵图\"",
      "\"像素动画\"",
      "\"复古动画\"",
      "od:",
      "mode: prototype"
    ]
  },
  {
    "id": "team-okrs",
    "name": "team-okrs",
    "description": "| OKR tracker page — quarter banner, three objectives with their key results as progress bars, owner avatars, status pills, and a \"this quarter at a glance\" sidebar. Use when the brief mentions \"OKRs\"",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"okr\"",
      "\"okrs\"",
      "\"key results\"",
      "\"objectives\"",
      "\"目标\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: product",
      "preview:",
      "type: html",
      "entry: index.html"
    ]
  },
  {
    "id": "trading-analysis-dashboard-template",
    "name": "trading-analysis-dashboard-template",
    "description": "| Professional trading analysis dashboard template (single-file HTML) with light/dark theme switch, dense market panels, chart interactions, demo/live playback, and command palette behavior. Use when ",
    "mode": "template",
    "tags": [],
    "triggers": [
      "\"trading analysis dashboard template\"",
      "\"wall street dashboard template\"",
      "\"financial terminal template\"",
      "\"trading cockpit template\"",
      "\"交易分析面板模板\"",
      "\"华尔街风格看板\"",
      "\"高科技金融 dashboard 模板\"",
      "od:",
      "mode: template",
      "platform: desktop",
      "scenario: live-artifacts",
      "preview:"
    ]
  },
  {
    "id": "tweaks",
    "name": "tweaks",
    "description": "| Wrap any HTML artifact with a side panel of live, parameterized controls — accent color, type scale, density, motion, theme — that rewrite CSS custom properties in real time and persist to localStor",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"tweaks\"",
      "\"variants\"",
      "\"tweak panel\"",
      "\"live controls\"",
      "\"adjust on the fly\"",
      "\"实时调参\"",
      "\"可调参数面板\"",
      "\"side panel\"",
      "\"knobs\"",
      "od:",
      "mode: prototype",
      "platform: desktop"
    ]
  },
  {
    "id": "video-shortform",
    "name": "video-shortform",
    "description": "| Short-form video generation skill — 3-10 second clips for product reveals, motion teasers, ambient loops. Defaults to Seedance 2 but works the same with Kling 3 / 4, Veo 3 or Sora 2. Output is one M",
    "mode": "video",
    "tags": [],
    "triggers": [
      "\"video\"",
      "\"clip\"",
      "\"shortform\"",
      "\"reel\"",
      "\"短视频\"",
      "\"动效\"",
      "od:",
      "mode: video",
      "surface: video",
      "scenario: marketing",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "waitlist-page",
    "name": "waitlist-page",
    "description": "| Minimal pre-launch landing with email capture, brand logo, and optional decorative layer. Reads DESIGN.md for colors, typography, and layout rules. Best for: product launches, beta signups, early ac",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"waitlist page\"",
      "\"coming soon page\"",
      "\"pre-launch landing page\"",
      "\"email capture page\"",
      "\"launch page\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: marketing",
      "preview:",
      "type: html",
      "entry: example.html"
    ]
  },
  {
    "id": "web-prototype",
    "name": "web-prototype",
    "description": "| General-purpose desktop web prototype. Single self-contained HTML file built by copying the seed `assets/template.html` and pasting section layouts from `references/layouts.md`. Default for any land",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"prototype\"",
      "\"mockup\"",
      "\"landing\"",
      "\"single page\"",
      "\"marketing page\"",
      "\"homepage\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: design",
      "preview:",
      "type: html"
    ]
  },
  {
    "id": "web-prototype-taste-brutalist",
    "name": "web-prototype-taste-brutalist",
    "description": "Swiss industrial-print web prototype. Newsprint canvas, monolithic black grotesque, viewport-bleeding numerals, hairline grid dividers, hazard-red accent, ASCII syntax decoration. Distilled from Leonx",
    "mode": "prototype",
    "tags": []
  },
  {
    "id": "web-prototype-taste-editorial",
    "name": "web-prototype-taste-editorial",
    "description": "Editorial-minimalist web prototype. Warm monochrome canvas, serif display + grotesque body, 1px hairline borders, muted pastel chips, generous macro-whitespace, ambient micro-motion. Distilled from Le",
    "mode": "prototype",
    "tags": []
  },
  {
    "id": "web-prototype-taste-soft",
    "name": "web-prototype-taste-soft",
    "description": "Apple-tier soft web prototype. Silver/cream canvas, double-bezel cards, button-in-button CTAs, generous squircle radii, spring motion, ambient mesh. Distilled from Leonxlnx/taste-skill `soft-skill` + ",
    "mode": "prototype",
    "tags": []
  },
  {
    "id": "webgl-experience",
    "name": "webgl-experience",
    "description": "| A full-screen, real-time WebGL/WebGL2 experience — animated shaders, 3D scenes, generative visuals, particle fields — rendered live on the GPU with a typographic overlay. Produced as a single self-c",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"webgl\"",
      "\"webgl2\"",
      "\"shader\"",
      "\"3d scene\"",
      "\"generative art\"",
      "\"gpu\"",
      "\"raymarch\"",
      "\"particle field\"",
      "\"interactive canvas\"",
      "\"着色器\"",
      "\"webgl 效果\"",
      "od:"
    ]
  },
  {
    "id": "weekly-update",
    "name": "weekly-update",
    "description": "| OpenDesign's weekly metrics standup: this week's numbers, the one anomaly, and the single decision it forces. Built as a decision-grade data & finance deck for ops & growth team. en_description: | O",
    "mode": "deck",
    "tags": [],
    "triggers": [
      "\"product-analytics-deck\"",
      "\"data-finance\"",
      "\"Run a Metrics Standup like a Data-Driven Ops Lead\"",
      "\"像数据驱动的运营负责人一样开指标站会\"",
      "\"kpi\"",
      "\"finance\"",
      "\"metrics\"",
      "\"html deck\"",
      "\"html slides\"",
      "od:",
      "mode: deck",
      "preview:"
    ]
  },
  {
    "id": "wireframe-annotated",
    "name": "wireframe-annotated",
    "description": "| An annotated / redline lo-fi wireframe — a desktop landing/marketing page drawn as flat greyboxes inside a browser chrome frame, overlaid with numbered annotation pins (①②③④⑤) in a single accent col",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"annotated wireframe\"",
      "\"redline\"",
      "\"wireframe spec\"",
      "\"lo-fi landing\"",
      "\"wireframe\"",
      "\"low fidelity\"",
      "\"标注线框图\"",
      "\"redline 标注\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: design"
    ]
  },
  {
    "id": "wireframe-greybox",
    "name": "wireframe-greybox",
    "description": "| A crisp greybox / blueprint lo-fi wireframe — neutral grey blocks on a pale page, image placeholders drawn as a rectangle with a diagonal X, text shown as solid \"lorem bars\" of varying widths, sharp",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"greybox\"",
      "\"grey box wireframe\"",
      "\"blueprint wireframe\"",
      "\"lo-fi dashboard\"",
      "\"low fidelity\"",
      "\"wireframe\"",
      "\"线框图\"",
      "\"灰盒\"",
      "od:",
      "mode: prototype",
      "platform: desktop",
      "scenario: design"
    ]
  },
  {
    "id": "wireframe-mobile-flow",
    "name": "wireframe-mobile-flow",
    "description": "| A lo-fi multi-screen MOBILE flow wireframe — three or four phone frames laid out in a row on a board, showing a connected user flow (Onboarding → Home feed → Item detail → Confirm). Grey-box content",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"mobile wireframe\"",
      "\"app flow\"",
      "\"user flow\"",
      "\"lo-fi mobile\"",
      "\"wireframe\"",
      "\"low fidelity\"",
      "\"移动端线框\"",
      "\"App 流程图\"",
      "od:",
      "mode: prototype",
      "platform: auto",
      "scenario: design"
    ]
  },
  {
    "id": "wireframe-sketch",
    "name": "wireframe-sketch",
    "description": "| A hand-drawn wireframe exploration — graph-paper background, marker / pencil tone, multiple tab labels for variants, sticky-note annotations, scribbled chart placeholders, hatched fills. Reads like ",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"wireframe\"",
      "\"sketch wireframe\"",
      "\"lo-fi mockup\"",
      "\"hand drawn\"",
      "\"whiteboard sketch\"",
      "\"low fidelity\"",
      "\"手绘原型\"",
      "\"草图\"",
      "\"线框图\"",
      "od:",
      "mode: prototype",
      "platform: desktop"
    ]
  },
  {
    "id": "worker-visualizer",
    "name": "worker-visualizer",
    "description": "| A real-time data/particle/simulation visualizer whose heavy compute runs in a Web Worker (off the main thread), optionally sharing memory with the UI via SharedArrayBuffer, and renders to a canvas a",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"web worker\"",
      "\"worker\"",
      "\"simulation\"",
      "\"particle system\"",
      "\"physics sim\"",
      "\"fractal\"",
      "\"off main thread\"",
      "\"sharedarraybuffer\"",
      "\"real-time compute\"",
      "\"visualizer\"",
      "\"多线程\"",
      "\"粒子\""
    ]
  },
  {
    "id": "x-research",
    "name": "x-research",
    "description": "| X/Twitter public sentiment research for recent market, company, product, or community discourse. Use when the brief asks what people are saying on X, Twitter sentiment, CT sentiment, public opinion,",
    "mode": "prototype",
    "tags": [],
    "triggers": [
      "\"x research\"",
      "\"twitter sentiment\"",
      "\"x/twitter\"",
      "\"what people are saying on x\"",
      "\"what twitter says\"",
      "\"ct sentiment\"",
      "\"public sentiment\"",
      "\"social sentiment\"",
      "\"推特情绪\"",
      "\"X 上怎么说\"",
      "od:",
      "mode: prototype"
    ]
  }
];
export const TEMPLATE_IDS = DESIGN_TEMPLATES.map(t => t.id);
